name: gtk-theme-orchis
architectures:
  - build-on: amd64
    run-on: all
version: '2022-05-29'
summary: Orchis theme
description: |
  Snap of the Orchis theme

# We build against Ubuntu 20.04 packages, but use the "bare" base as
# we don't want to force installation of a large base snap.
build-base: core20
base: bare
grade: stable
confinement: strict

slots:
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Orchis-Light
        - $SNAP/share/themes/Orchis-Light-Compact
        - $SNAP/share/themes/Orchis-Dark
        - $SNAP/share/themes/Orchis-Dark-Compact
        - $SNAP/share/themes/Orchis-Compact

parts:
  theme:
    plugin: dump
    source: https://github.com/vinceliuice/Orchis-theme/archive/refs/tags/2022-05-29.tar.gz
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes/
        $SNAPCRAFT_PART_SRC/install.sh -d $SNAPCRAFT_PART_INSTALL/share/themes/

    build-packages:
      - gtk-update-icon-cache
    organize:
      install/share/themes/Orchis*: share/themes/*
